const guns = [
  {
    name: "All",
    img: "all.png",
  },
  {
    name: "Advanced Rifle",
    img: "advancedrifle.png",
    weapon: "advancedrifle",
    type: "rifle",
  },
  {
    name: "AP Pistol",
    img: "appistol.png",
    weapon: "appistol",
    type: "pistol",
  },
  {
    name: "Assult Rifle MK II",
    img: "assaultrifle_mk2.png",
    weapon: "assaultrifle_mk2",
    type: "rifle",
  },
  {
    name: "Assult Rifle",
    img: "assaultrifle.png",
    weapon: "assaultrifle",
    type: "rifle",
  },
  {
    name: "Assult Shotgun",
    img: "assaultshotgun.png",
    weapon: "assaultshotgun",
    type: "shotgun",
  },
  {
    name: "Assult SMG",
    img: "assaultsmg.png",
    weapon: "assaultsmg",
    type: "smg",
  },
  {
    name: "Auto Shotgun",
    img: "autoshotgun.png",
    weapon: "autoshotgun",
    type: "shotgun",
  },
  {
    name: "Bullpup Rifle MK II",
    img: "bullpuprifle_mk2.png",
    weapon: "bullpuprifle_mk2",
    type: "rifle",
  },
  {
    name: "Bullpup Rifle",
    img: "bullpuprifle.png",
    weapon: "bullpuprifle",
    type: "rifle",
  },
  {
    name: "Bullpup Shotgun",
    img: "bullpupshotgun.png",
    weapon: "bullpupshotgun",
    type: "shotgun",
  },
  {
    name: "Carbine Rifle MK II",
    img: "carbinerifle_mk2.png",
    weapon: "carbinerifle_mk2",
    type: "rifle",
  },
  {
    name: "Carbine Rifle",
    img: "carbinerifle.png",
    weapon: "carbinerifle",
    type: "rifle",
  },
  {
    name: "Combat MG MK II",
    img: "combatmg_mk2.png",
    weapon: "combatmg_mk2",
    type: "lmg",
  },
  {
    name: "Combat MG",
    img: "combatmg.png",
    weapon: "combatmg",
    type: "lmg",
  },
  {
    name: "Combat PDW",
    img: "combatpdw.png",
    weapon: "combatpdw",
    type: "smg",
  },
  {
    name: "Combat Pistol",
    img: "combatpistol.png",
    weapon: "combatpistol",
    type: "pistol",
  },
  {
    name: "Compact Rifle",
    img: "compactrifle.png",
    weapon: "compactrifle",
    type: "rifle",
  },
  {
    name: "Double Barrel Shotgun",
    img: "dbshotgun.png",
    weapon: "dbshotgun",
    type: "shotgun",
  },
  {
    name: "Double-Action Revolver",
    img: "doubleaction.png",
    weapon: "doubleaction",
    type: "pistol",
  },
  {
    name: "Gunsenberg Sweeper",
    img: "gusenberg.png",
    weapon: "gusenberg",
    type: "smg",
  },
  {
    name: "Heavy Pistol",
    img: "heavypistol.png",
    weapon: "heavypistol",
    type: "pistol",
  },
  {
    name: "Heavy Shotgun",
    img: "heavyshotgun.png",
    weapon: "heavyshotgun",
    type: "shotgun",
  },
  {
    name: "Heavy Sniper MK II",
    img: "heavysniper_mk2.png",
    weapon: "heavysniper_mk2",
    type: "sniper",
  },
  {
    name: "Heavy Sniper",
    img: "heavysniper.png",
    weapon: "heavysniper",
    type: "sniper",
  },
  {
    name: "Machine Pistol",
    img: "machinepistol.png",
    weapon: "machinepistol",
    type: "lmg",
  },
  {
    name: "Marksman Pistol",
    img: "marksmanpistol.png",
    weapon: "marksmanpistol",
    type: "pistol",
  },
  {
    name: "Marksman Rifle MK II",
    img: "marksmanrifle_mk2.png",
    weapon: "marksmanrifle_mk2",
    type: "sniper",
  },
  {
    name: "Marksman Rifle",
    img: "marksmanrifle.png",
    weapon: "marksmanrifle",
    type: "sniper",
  },
  {
    name: "MG",
    img: "mg.png",
    weapon: "mg",
    type: "lmg",
  },
  {
    name: "Micro SMG",
    img: "microsmg.png",
    weapon: "microsmg",
    type: "smg",
  },
  {
    name: "Mini Gun",
    img: "minigun.png",
    weapon: "minigun",
    type: "lmg",
  },
  {
    name: "Mini SMG",
    img: "minismg.png",
    weapon: "minismg",
    type: "smg",
  },
  // {
  //   name: "Musket",
  //   img: "musket.png",
  //   weapon: "musket",
  //   type: "rifle",
  // },
  {
    name: "Pistol .50",
    img: "pistol50.png",
    weapon: "pistol50",
    type: "pistol",
  },
  {
    name: "Pistol MK II",
    img: "pistol_mk2.png",
    weapon: "pistol_mk2",
    type: "pistol",
  },
  {
    name: "Pistol",
    img: "pistol.png",
    weapon: "pistol",
    type: "pistol",
  },
  {
    name: "Pump Shotgun",
    img: "pumpshotgun.png",
    weapon: "pumpshotgun",
    type: "shotgun",
  },
  {
    name: "Pump Shotgun MK II",
    img: "pumpshotgun_mk2.png",
    weapon: "pumpshotgun_mk2",
    type: "shotgun",
  },
  {
    name: "Revolver MK II",
    img: "revolver_mk2.png",
    weapon: "revolver_mk2",
    type: "pistol",
  },
  {
    name: "Revolver",
    img: "revolver.png",
    weapon: "revolver",
    type: "pistol",
  },
  {
    name: "Sawn-Off Shotgun",
    img: "sawnoffshotgun.png",
    weapon: "sawnoffshotgun",
    type: "shotgun",
  },
  {
    name: "SMG MK II",
    img: "smg_mk2.png",
    weapon: "smg_mk2",
    type: "smg",
  },
  {
    name: "SMG",
    img: "smg.png",
    weapon: "smg",
    type: "smg",
  },
  {
    name: "SNS Pistol MK II",
    img: "snspistol_mk2.png",
    weapon: "snspistol_mk2",
    type: "pistol",
  },
  {
    name: "SNS Pistol",
    img: "snspistol.png",
    weapon: "snspistol",
    type: "pistol",
  },
  {
    name: "Special Carbine MK II",
    img: "specialcarbine_mk2.png",
    weapon: "specialcarbine_mk2",
    type: "rifle",
  },
  {
    name: "Special Carbine",
    img: "specialcarbine.png",
    weapon: "specialcarbine",
    type: "rifle",
  },
  {
    name: "Vintage Pistol",
    img: "vintagepistol.png",
    weapon: "vintagepistol",
    type: "pistol",
  },
];

export default guns;
