vehicleCrimes = {
    { id = 1, name = "Speeding", fine = 300, description = "Exceeding speed limit" },
    { id = 2, name = "Illegal Parking", fine = 200, description = "Parking in restricted area" },
    { id = 3, name = "Reckless Driving", fine = 1000, description = "Driving dangerously" },
    { id = 4, name = "Driving Without License", fine = 800, description = "Operating vehicle without valid license" },
    { id = 5, name = "Car Theft", fine = 4000, description = "Stealing a vehicle" },
    { id = 6, name = "DUI", fine = 1500, description = "Driving under the influence" },
    { id = 7, name = "Red Light Violation", fine = 350, description = "Running a red light" },
    { id = 8, name = "Hit and Run", fine = 2500, description = "Fleeing scene after accident" },
    { id = 9, name = "Illegal U-turn", fine = 300, description = "Making a prohibited U-turn" },
    { id = 10, name = "No Insurance", fine = 900, description = "Driving without valid insurance" },
    { id = 11, name = "Expired Registration", fine = 250, description = "Driving with expired vehicle registration" },
    { id = 12, name = "Failure to Signal", fine = 150, description = "Not signaling while turning" },
    { id = 13, name = "Tailgating", fine = 400, description = "Following another car too closely" },
    { id = 14, name = "Illegal Modifications", fine = 600, description = "Using unapproved vehicle modifications" },
    { id = 15, name = "Illegal Window Tint", fine = 200, description = "Using unauthorized window tint" },
    { id = 16, name = "Evading Police", fine = 3000, description = "Running from police in a vehicle" },
    { id = 17, name = "Burnout/Drifting", fine = 700, description = "Performing burnouts or drifting" },
    { id = 18, name = "Wrong Way Driving", fine = 500, description = "Driving in opposite direction of traffic" },
    { id = 19, name = "Obstructing Traffic", fine = 350, description = "Blocking road intentionally" },
    { id = 20, name = "Failure to Yield", fine = 300, description = "Not yielding at an intersection" },
    { id = 21, name = "Using Phone While Driving", fine = 200, description = "Texting or calling while driving" },
    { id = 22, name = "Street Racing", fine = 3500, description = "Racing on public roads" },
    { id = 23, name = "Driving Without Helmet", fine = 250, description = "No helmet on a motorcycle" },
    { id = 24, name = "No Seatbelt", fine = 150, description = "Not wearing a seatbelt" },
    { id = 25, name = "Using Off-road Areas", fine = 400, description = "Driving on sidewalks or non-road areas" },
    { id = 26, name = "Driving With Broken Lights", fine = 300, description = "Non-functional headlights or taillights" },
    { id = 27, name = "Transporting Illegal Goods", fine = 5000, description = "Using vehicle for illegal cargo" },
    { id = 28, name = "Improper Lane Change", fine = 300, description = "Unsafe or abrupt lane switching" },
    { id = 29, name = "Blocking Emergency Vehicle", fine = 800, description = "Failing to make way for emergency vehicles" },
    { id = 30, name = "Driving on Shoulder", fine = 350, description = "Using emergency lane illegally" },
    { id = 31, name = "Failure to Stop at Stop Sign", fine = 400, description = "Running a stop sign" },
    { id = 32, name = "Driving Unregistered Vehicle", fine = 700, description = "No vehicle registration" },
    { id = 33, name = "Driving With Suspended License", fine = 1200, description = "License suspension ignored" },
    { id = 34, name = "Blocking Fire Hydrant", fine = 250, description = "Parking next to fire hydrant" },
    { id = 35, name = "Unauthorized Emergency Lights", fine = 1500, description = "Installing fake sirens/lights" },
    { id = 36, name = "Aggressive Driving", fine = 750, description = "Road rage / aggression on road" },
    { id = 37, name = "Engine Idling Violation", fine = 100, description = "Leaving engine running while parked" },
    { id = 38, name = "Unsecure Load", fine = 300, description = "Unsecured cargo falling from vehicle" },
    { id = 39, name = "Using Horn Excessively", fine = 100, description = "Noise disturbance from honking" },
    { id = 40, name = "Tampering With Traffic Signs", fine = 2000, description = "Altering road signs illegally" },
    { id = 41, name = "Driving With Broken Windshield", fine = 250, description = "Cracked windshield not fixed" },
    { id = 42, name = "Excessive Smoke Emission", fine = 500, description = "Vehicle polluting excessively" },
    { id = 43, name = "Driving With Open Alcohol", fine = 1000, description = "Alcohol container in vehicle" },
    { id = 44, name = "Driving in Bus Lane", fine = 300, description = "Unauthorized use of bus lanes" },
    { id = 45, name = "Driving Through Barricade", fine = 800, description = "Crossing blocked roads" },
    { id = 46, name = "Unlawful Use of Horn", fine = 150, description = "Honking in restricted area" },
    { id = 47, name = "Driving Without Rearview Mirror", fine = 200, description = "Missing safety mirrors" },
    { id = 48, name = "Failure to Dim Headlights", fine = 150, description = "Blinding other drivers" },
    { id = 49, name = "Driving Too Slowly", fine = 200, description = "Obstructing traffic by slow speed" },
    { id = 50, name = "Blocking Intersection", fine = 300, description = "Stopping inside junction" }
}

personalCrimes = {
    { id = 1, name = "Murder", fine = 20000, description = "Unlawful killing of another person" },
    { id = 2, name = "Attempted Murder", fine = 15000, description = "Attempting to kill someone" },
    { id = 3, name = "Assault", fine = 3000, description = "Physical harm to another person" },
    { id = 4, name = "Battery", fine = 3500, description = "Violent physical attack" },
    { id = 5, name = "Kidnapping", fine = 10000, description = "Unlawfully taking someone by force" },
    { id = 6, name = "Hostage Taking", fine = 12000, description = "Holding someone against their will" },
    { id = 7, name = "Armed Robbery", fine = 8000, description = "Theft with use of weapons" },
    { id = 8, name = "Robbery", fine = 6000, description = "Stealing from someone using force" },
    { id = 9, name = "Burglary", fine = 5000, description = "Unlawfully entering property to commit crime" },
    { id = 10, name = "Home Invasion", fine = 7000, description = "Entering home with intent to commit crime" },
    { id = 11, name = "Theft", fine = 2500, description = "Stealing property" },
    { id = 12, name = "Pickpocketing", fine = 1500, description = "Stealing from pockets/bags" },
    { id = 13, name = "Fraud", fine = 4000, description = "Deceiving to gain money or assets" },
    { id = 14, name = "Forgery", fine = 3500, description = "Faking documents/signatures" },
    { id = 15, name = "Identity Theft", fine = 5000, description = "Using someone else's identity" },
    { id = 16, name = "Drug Possession", fine = 3000, description = "Possessing illegal substances" },
    { id = 17, name = "Drug Distribution", fine = 7000, description = "Selling illegal substances" },
    { id = 18, name = "Drug Manufacturing", fine = 9000, description = "Producing illegal substances" },
    { id = 19, name = "Public Intoxication", fine = 1000, description = "Being drunk in public" },
    { id = 20, name = "Disturbing the Peace", fine = 1200, description = "Disrupting public order" },
    { id = 21, name = "Trespassing", fine = 800, description = "Unlawfully entering private property" },
    { id = 22, name = "Vandalism", fine = 2000, description = "Damaging property intentionally" },
    { id = 23, name = "Graffiti", fine = 1000, description = "Spray painting walls without permission" },
    { id = 24, name = "Harassment", fine = 1500, description = "Unwanted, repeated attention" },
    { id = 25, name = "Threatening", fine = 1800, description = "Threats of violence or harm" },
    { id = 26, name = "Intimidation", fine = 1600, description = "Scaring others into submission" },
    { id = 27, name = "Bribery", fine = 4000, description = "Offering money for influence" },
    { id = 28, name = "Obstruction of Justice", fine = 3500, description = "Interfering with legal process" },
    { id = 29, name = "Resisting Arrest", fine = 2500, description = "Refusing to comply with arrest" },
    { id = 30, name = "Escape from Custody", fine = 6000, description = "Fleeing police/jail unlawfully" },
    { id = 31, name = "False Report", fine = 2200, description = "Lying to authorities" },
    { id = 32, name = "Witness Tampering", fine = 5500, description = "Influencing witnesses illegally" },
    { id = 33, name = "Perjury", fine = 3000, description = "Lying under oath" },
    { id = 34, name = "Blackmail", fine = 5000, description = "Threatening for personal gain" },
    { id = 35, name = "Extortion", fine = 5500, description = "Forcing payment through threats" },
    { id = 36, name = "Cybercrime", fine = 4000, description = "Committing crimes via computers" },
    { id = 37, name = "Illegal Gambling", fine = 1800, description = "Running unauthorized betting" },
    { id = 38, name = "Organized Crime", fine = 10000, description = "Participating in crime syndicates" },
    { id = 39, name = "Corruption", fine = 6000, description = "Abuse of power for gain" },
    { id = 40, name = "Sexual Assault", fine = 15000, description = "Non-consensual sexual contact" },
    { id = 41, name = "Indecent Exposure", fine = 2000, description = "Showing nudity in public" },
    { id = 42, name = "Solicitation", fine = 1800, description = "Offering sexual services" },
    { id = 43, name = "Human Trafficking", fine = 20000, description = "Trading people illegally" },
    { id = 44, name = "Child Abuse", fine = 15000, description = "Causing harm to a minor" },
    { id = 45, name = "Animal Cruelty", fine = 2200, description = "Harming or neglecting animals" },
    { id = 46, name = "Arson", fine = 5000, description = "Intentionally setting fire" },
    { id = 47, name = "Looting", fine = 2500, description = "Stealing during emergencies" },
    { id = 48, name = "Possession of Stolen Goods", fine = 3000, description = "Holding stolen items" },
    { id = 49, name = "Impersonating Officer", fine = 4000, description = "Faking authority role" },
    { id = 50, name = "Contempt of Court", fine = 2000, description = "Disobeying court authority" }
}
