drugsList = {
    { drug = "Paracetamol", brand = "Tylenol", type = "Analgesic / Antipyretic" },
    { drug = "Ibuprofen", brand = "Advil", type = "NSAID" },
    { drug = "Amoxicillin", brand = "Amoxil", type = "Antibiotic" },
    { drug = "Ciprofloxacin", brand = "Cipro", type = "Antibiotic" },
    { drug = "Metformin", brand = "Glucophage", type = "Antidiabetic" },
    { drug = "Omeprazole", brand = "Prilosec", type = "Proton Pump Inhibitor" },
    { drug = "Loratadine", brand = "Claritin", type = "Antihistamine" },
    { drug = "Cetirizine", brand = "Zyrtec", type = "Antihistamine" },
    { drug = "Tramadol", brand = "Ultram", type = "Opioid Analgesic" },
    { drug = "Aspirin", brand = "Bayer", type = "Antiplatelet / Analgesic" },
    { drug = "Atorvastatin", brand = "Lipitor", type = "Cholesterol Lowering" },
    { drug = "Salbutamol", brand = "Ventolin", type = "Bronchodilator" },
    { drug = "Hydrochlorothiazide", brand = "Microzide", type = "Diuretic" },
    { drug = "Diazepam", brand = "Valium", type = "Anxiolytic / Muscle Relaxant" },
    { drug = "Clopidogrel", brand = "Plavix", type = "Antiplatelet" },
    { drug = "Prednisone", brand = "Deltasone", type = "Corticosteroid" },
    { drug = "Insulin Glargine", brand = "Lantus", type = "Insulin" },
    { drug = "Furosemide", brand = "Lasix", type = "Loop Diuretic" },
    { drug = "Ranitidine", brand = "Zantac", type = "H2 Blocker (Antacid)" },
    { drug = "Azithromycin", brand = "Zithromax", type = "Macrolide Antibiotic" },
    { drug = "Naproxen", brand = "Aleve", type = "NSAID" },
    { drug = "Codeine", brand = "Tylenol #3", type = "Opioid Analgesic" },
    { drug = "Ketorolac", brand = "Toradol", type = "Pain Reliever (NSAID)" },
    { drug = "Morphine", brand = "MS Contin", type = "Strong Opioid" },
    { drug = "Pantoprazole", brand = "Protonix", type = "Proton Pump Inhibitor" },
    { drug = "Alprazolam", brand = "Xanax", type = "Benzodiazepine" },
    { drug = "Metronidazole", brand = "Flagyl", type = "Antibiotic / Antiprotozoal" },
    { drug = "Doxycycline", brand = "Vibramycin", type = "Tetracycline Antibiotic" },
    { drug = "Fluoxetine", brand = "Prozac", type = "Antidepressant (SSRI)" },
    { drug = "Sertraline", brand = "Zoloft", type = "Antidepressant (SSRI)" }
}
