-- File generated with VMS Garages V2 - Parking Creator.

Config = Config or {}

while not Config.Garages do
    Citizen.Wait(100)
end

Config.Garages['ambulance'] = {
    label = 'ambulance',
    type = 'vehicle',

    requiredJob = {
        ['ambulance'] = true,
    },

    nameBlip = 'job_garage',
    showBlip = false,
    blipCoords = vec3(-844.3998413086, -1238.4517822266, 6.908959388733),

    garageZone = {
        vec2(-855.533203125, -1204.0831298828),
        vec2(-874.6567993164, -1218.5480957032),
        vec2(-865.50012207032, -1237.66015625),
        vec2(-837.11151123046, -1262.1604003906),
        vec2(-820.7841796875, -1236.0494384766),
    },
    minZ = -0.2636947631836,
    maxZ = 64.736305236816,

    availableVehicles = {
        ['Killer_ems6'] = {
                model = 'Killer_ems6',
                gradesAccess = { 0, 1, 2, 3, 4, 5, 6, 7, 8 },
                customProperties = {
                    ['modEngine'] = 3,
                    ['modBrakes'] = 2,
                    ['modTransmission'] = 2,
                    ['modArmor'] = 4,
                    ['modTurbo'] = true,
                    ['windowTint'] = 3,
                    ['modLivery'] = 1,
                    ['extras'] = {
                        [0] = true,
                        [1] = true,
                        [2] = true,
                        [3] = true,
                        [4] = true,
                        [5] = true,
                        [6] = true,
                        [7] = true,
                        [8] = true,
                        [9] = true,
                        [10] = true,
                        [11] = true,
                    },
                },
            },
            ['Killer_ems5'] = {
                model = 'Killer_ems5',
                gradesAccess = { 0, 1, 2, 3, 4, 5, 6, 7, 8 },
                customProperties = {
                    ['modEngine'] = 3,
                    ['modBrakes'] = 2,
                    ['modTransmission'] = 2,
                    ['modArmor'] = 4,
                    ['modTurbo'] = true,
                    ['windowTint'] = 3,
                    ['modLivery'] = 1,
                    ['extras'] = {
                        [0] = true,
                        [1] = true,
                        [2] = true,
                        [3] = true,
                        [4] = true,
                        [5] = true,
                        [6] = true,
                        [7] = true,
                        [8] = true,
                        [9] = true,
                        [10] = true,
                        [11] = true,
                    },
                },
            },
            ['Killer_ems4'] = {
                model = 'Killer_ems4',
                gradesAccess = { 0, 1, 2, 3, 4, 5, 6, 7, 8 },
                customProperties = {
                    ['modEngine'] = 3,
                    ['modBrakes'] = 2,
                    ['modTransmission'] = 2,
                    ['modArmor'] = 4,
                    ['modTurbo'] = true,
                    ['windowTint'] = 3,
                    ['modLivery'] = 1,
                    ['extras'] = {
                        [0] = true,
                        [1] = true,
                        [2] = true,
                        [3] = true,
                        [4] = true,
                        [5] = true,
                        [6] = true,
                        [7] = true,
                        [8] = true,
                        [9] = true,
                        [10] = true,
                        [11] = true,
                    },
                },
            },
            ['Killer_ems3'] = {
                model = 'Killer_ems3',
                gradesAccess = { 0, 1, 2, 3, 4, 5, 6, 7, 8 },
                customProperties = {
                    ['modEngine'] = 3,
                    ['modBrakes'] = 2,
                    ['modTransmission'] = 2,
                    ['modArmor'] = 4,
                    ['modTurbo'] = true,
                    ['windowTint'] = 3,
                    ['modLivery'] = 1,
                    ['extras'] = {
                        [0] = true,
                        [1] = true,
                        [2] = true,
                        [3] = true,
                        [4] = true,
                        [5] = true,
                        [6] = true,
                        [7] = true,
                        [8] = true,
                        [9] = true,
                        [10] = true,
                        [11] = true,
                    },
                },
            },
            ['Killer_ems2'] = {
                model = 'Killer_ems2',
                gradesAccess = { 0, 1, 2, 3, 4, 5, 6, 7, 8 },
                customProperties = {
                    ['modEngine'] = 3,
                    ['modBrakes'] = 2,
                    ['modTransmission'] = 2,
                    ['modArmor'] = 4,
                    ['modTurbo'] = true,
                    ['windowTint'] = 3,
                    ['modLivery'] = 1,
                    ['extras'] = {
                        [0] = true,
                        [1] = true,
                        [2] = true,
                        [3] = true,
                        [4] = true,
                        [5] = true,
                        [6] = true,
                        [7] = true,
                        [8] = true,
                        [9] = true,
                        [10] = true,
                        [11] = true,
                    },
                },
            },
    },
	npc = {
            enabled = true,
            model = 'u_m_y_baygor',
            animation = { 'rcmnigel1a', 'base' },
            coords = vector4(-844.17, -1239.47, 5.90, 53.44),
        },
    menuPoint = vec3(-844.63, -1239.19, 6.91),
    garageData = {
        pedCoords = vec4(-856.02, -1215.03, 6.12, 301.63),
        vehicleCoords = vec4(-859.01, -1217.27, 5.70, 339.32),
        cameraCoords = vec3(-849.88, -1213.76, 6.33),
        cameraFov = 50.0,
    },

    spawnPoint = vec4(-853.01251220704, -1233.344116211, 6.49515914917, 320.0),
    checkAreaOccupied = true,
    returnVehiclePoint = vec3(-849.8433227539, -1237.9532470704, 6.90895986557),
}